#!/usr/bin/python
import argparse
import os

excluded_dirs = ['.git', 'build', 'papers']
subdirs = [o for o in os.listdir('.') if os.path.isdir(os.path.join('.', o)) and o not in excluded_dirs]
subdirs.sort()
print(subdirs)

parser = argparse.ArgumentParser(description='Creating new research files dynamically with little effort.')
parser.add_argument('-c', '--category', required=True, type=str, help='Specify the category for which this research belongs. The available categories are: ' + ', '.join([d for d in subdirs]))
parser.add_argument('-n', '--name', required=True, type=str, help='Name the file and section reference')


args = parser.parse_args()

# Create the directory if it doesnt exist
if not os.path.exists(args.category):

    # Create the directory
    os.makedirs(args.category)

    # Create the header file in the directory
    # TODO: Make the header file automatically read from all the other files in
    # the folder rather than inputting them manually via this command line tool
    with open(f'{args.category}/header.tex', 'w+') as f:
        f.write(f'\\part{{{args.category}}}\n')

    # Attach the header file to the overarching directory folder
    with open('directories.tex', 'a') as f:
        f.write(f'\\import{{{args.category}/}}{{header}}\n')

    print(f'New directory created at {args.category}')


with open(f'{args.category}/{args.name}.tex', 'w+') as f:
    f.write(f'\\chapter{{\\sectioncite{{{args.name}}}}}\n')
    f.write(f'\\label{{cha:{args.name}}}\n\n')
    f.write(f'\\TODO{{(Read the paper and insert information here.)}}')

with open(f'{args.category}/header.tex', 'a') as f:
    f.write(f'\\import{{}}{{{args.name}}}\n')
    
print(f'New file created at {args.category}/{args.name}.tex')
print("Completed successfully!")
